server:
  port: ${PORT:8080}

spring:
  application:
    name: "BackendAccentureReactive"

  # 1. Configuración Reactiva (R2DBC)
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/franquicias_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    pool:
      initial-size: ${DB_POOL_INIT:5}
      max-size: ${DB_POOL_MAX:20}

  # 2. Configuración de Migraciones
  flyway:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/franquicias_db}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui.path: "/v3/swagger-ui.html"
  api-docs.path: "/v3/api-docs"

cors:
  allowed-origins: ${CORS_ALLOWED:http://localhost:4200,http://localhost:8080}