services:
  postgres-test:
    image: postgres:16-alpine
    container_name: backend-accenture-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: accenture_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d accenture_db_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7.2-alpine
    container_name: backend-accenture-redis-test
    restart: unless-stopped
    ports:
      - "56379:6379"
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
